name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Windows portable executable
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Download dependencies
        run: yarn install --frozen-lockfile
      - name: Build the executable
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
