name: Build executable

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build executable
    strategy:
      matrix:
        os: [windows-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Download dependencies
        run: npm ci
      - name: Build executable
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
